/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AIWalletConfig } from "./components/ai-wallet/ai-wallet";
export { AIWalletConfig } from "./components/ai-wallet/ai-wallet";
export namespace Components {
    interface AiWallet {
        /**
          * @default ["vlm", "llm", "sst", "tts"]
         */
        "capabilities": any;
        "cardTitle": string;
        "getConfiguration": () => Promise<AIWalletConfig>;
        "getRemoteStorage": () => Promise<any>;
        "saveConfiguration": () => Promise<boolean>;
        "setRemoteStorage": (rs: any) => Promise<void>;
        "subtitle": string;
        /**
          * @default true
         */
        "sync": boolean;
        /**
          * @default 'shadow'
         */
        "variant": 'shadow' | 'border';
    }
    interface ConnectRemotestorage {
        "rs": any;
    }
}
export interface AiWalletCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAiWalletElement;
}
declare global {
    interface HTMLAiWalletElementEventMap {
        "configChanged": AIWalletConfig;
    }
    interface HTMLAiWalletElement extends Components.AiWallet, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAiWalletElementEventMap>(type: K, listener: (this: HTMLAiWalletElement, ev: AiWalletCustomEvent<HTMLAiWalletElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAiWalletElementEventMap>(type: K, listener: (this: HTMLAiWalletElement, ev: AiWalletCustomEvent<HTMLAiWalletElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAiWalletElement: {
        prototype: HTMLAiWalletElement;
        new (): HTMLAiWalletElement;
    };
    interface HTMLConnectRemotestorageElement extends Components.ConnectRemotestorage, HTMLStencilElement {
    }
    var HTMLConnectRemotestorageElement: {
        prototype: HTMLConnectRemotestorageElement;
        new (): HTMLConnectRemotestorageElement;
    };
    interface HTMLElementTagNameMap {
        "ai-wallet": HTMLAiWalletElement;
        "connect-remotestorage": HTMLConnectRemotestorageElement;
    }
}
declare namespace LocalJSX {
    interface AiWallet {
        /**
          * @default ["vlm", "llm", "sst", "tts"]
         */
        "capabilities"?: any;
        "cardTitle"?: string;
        "onConfigChanged"?: (event: AiWalletCustomEvent<AIWalletConfig>) => void;
        "subtitle"?: string;
        /**
          * @default true
         */
        "sync"?: boolean;
        /**
          * @default 'shadow'
         */
        "variant"?: 'shadow' | 'border';
    }
    interface ConnectRemotestorage {
        "rs"?: any;
    }
    interface IntrinsicElements {
        "ai-wallet": AiWallet;
        "connect-remotestorage": ConnectRemotestorage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ai-wallet": LocalJSX.AiWallet & JSXBase.HTMLAttributes<HTMLAiWalletElement>;
            "connect-remotestorage": LocalJSX.ConnectRemotestorage & JSXBase.HTMLAttributes<HTMLConnectRemotestorageElement>;
        }
    }
}
